# Generated by Django 3.1.2 on 2021-05-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planos',
            new_name='Plano',
        ),
        migrations.AlterField(
            model_name='question',
            name='responses',
            field=models.JSONField(default=None, null=True, verbose_name='Respostas'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.JSONField(default=None, null=True, verbose_name='Tipos de questões'),
        ),
    ]
